---

- hosts: all
  become: true

  tasks:


  - name: Install Apache Web Server Package
    yum:
      name: httpd
      state: present

  
  - name: Enable and start httpd service
    systemd:
      name: httpd
      enabled: true
      state: started 


  - name: Add http service to firewall
    firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled


...
