---

- hosts: all
  become: true
  #pre_tasks: <<< This allows for tasks to be ran first before other tasks that may be defined in this playbook

  tasks:


  - name: Install Apache Web Server Package
    #tags: always         << adding tags will let ansible know to always run this play. You can also use it to target certain servers. With that being said, you can use whatever tag name you want.
    #To see the tags on the CLI: ansible-playbook --list-tags [yaml file]
    #To run the playbook using the tag: ansible-playbook --tags [tag name] --ask-become-pass [yaml file] 
    yum:
      name: httpd
      state: present
      update_cache: true

  
  - name: Enable and start httpd service
    systemd:
      name: httpd
      enabled: true
      state: started 


  - name: Add http service to firewall
    #tags: db
    firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled
        #when: ansible_hostname == "dbserver1-treadtech"


...
