---

- hosts: all
  become: true
  #pre_tasks: <<< This allows for tasks to be ran first before other tasks that may be defined in this playbook

  tasks:


  - name: Install Apache Web Server Package
    #tags: always         << adding tags will let ansible know to always run this play. You can also use it to target certain servers. With that being said, you can use whatever tag name you want.
    #To see the tags on the CLI: ansible-playbook --list-tags [yaml file]
    #To run the playbook using the tag: ansible-playbook --tags [tag name] --ask-become-pass [yaml file] 
    yum:
      name: httpd
      state: present
      update_cache: true

  
  - name: Enable and start httpd service
    systemd:
      name: httpd
      enabled: true
      state: started 


  - name: Add http service to firewall
    #tags: db
    firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled
        #when: ansible_hostname == "dbserver1-treadtech"
  

  - name: Copy default html file for site
    copy:
      src: default_site.html # In ansible, the file directory is assumed already. All you have to do is put the file name and Ansible will know where to get it from.
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: Install unzip 
    package:
      name: unzip

  
  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_darwin_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  

  - name: Start httpd service
    service:
      name: httpd
      state: started
      enabled: yes


  - name: change e-mail address for admin
    lineinfile: # This ansible module adds a line in a file
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin' # This is a regex expression that identifies the line that starts with a certain word
      line: ServerAdmin somebody@somewhere.net # This is the line you would add to the file 
    register: httpd # Register captures this state in a variable. So when this play is ran, it'll notice Ansible of the change. If you are going to change multiple lines, you have to use a different variable name. It's going to make a change and will only register the most recent change if you use the same name. Create a whole new play and use a different name for the register variable.


  - name: Restart httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed # This is monitoring the register variable above. So when it notices a change, this play will be ran.


- hosts: all
  become: true
  tasks:

  
  # This play will be adding an authorized key for that user. We want ansible to login as an administrator using wwhite without a password or passphrase. We are allowing administrators with this key to log in without a password
  - name: add ssh key for wwhite
    authorized_key:
      user: wwhite
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMnK6DORMhOwmCAwOROLSXpFYw8Ad7aoV8IXl0COnjC0 ansible"


       
...
